### ISSUE TITLE
New Chapter for Blacksburg, Virginia

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#214] opened 2016-11-08 20:03 UTC
__Summary__
Maptime name: __MaptimeVirginiaTech__
Contact name: Beth Bodner
Date submitted: 2016-11-08 20:01:21

- [ ] Add GH admins to new team: 
- [ ] Add Location (Blacksburg, Virginia) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment] 2016-11-13 21:17
Duplicate of #208

**Closed as completed by geobrando** 2016-11-13 21:17 UTC
Labels: repo request
