### ISSUE TITLE
New Chapter for Christchurch, New Zealand

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#258] opened 2019-04-03 05:20 UTC
__Summary__
Maptime name: __MaptimeChristchurch__
Contact name: Andrew Douglas-Clifford
Date submitted: 2019-04-03 05:20:41

- [ ] Add GH admins to new team: Yes
- [ ] Add Location (Christchurch, New Zealand) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by philam** [comment] 2019-04-11 22:23
Hi there! Would you be able to post your GitHub username please?

**Comment by geobrando** [comment] 2022-04-28 13:21
Duplicate of #256

**Closed as completed by geobrando** 2022-04-28 13:21 UTC
Labels: repo request
