### ISSUE TITLE
New Chapter for GeoFort, Netherlands

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#195] opened 2016-07-28 16:20 UTC
**Summary**
Maptime name: **MaptimeSummercamp**
Contact name: Erik Meerburg
Date submitted: 2016-07-28 16:05:32
- [ ] Add GH admins to new team: 
- [ ] Add Location (GeoFort, Netherlands) to chapters.json and /chapters page.

**Additional tasks**
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment] 2016-07-28 19:10
Duplicate of #189

**Closed as completed by almccon** 2016-07-28 19:10 UTC
Labels: repo request
